const Data = {
  products: [
    {
      id: '32HL4300HA',
      name: 'Televizor LED Diamant, 80 cm, 32HL4300H/A, HD',
      category: 'electronics',
      img: [
        '/img/products/product-1.png',
        '/img/products/product-1-1.png',
        '/img/products/product-1-2.png',
        '/img/products/product-1-3.png',
        '/img/products/product-1-4.png',
      ],
      price: 699,
      onSale: true,
      salePrice: 449,
      rating: 4.5,
      reviews: 367,
      stock: 11,
    },
    {
      id: 'PD914DB',
      name: 'Aspirator cu sac Electrolux PD91-4DB, 550W, 5 l',
      category: 'electronics',
      img: [
        '/img/products/product-2.png',
        '/img/products/product-2-1.png',
        '/img/products/product-2-2.png',
        '/img/products/product-2-3.png',
        '/img/products/product-2-4.png',
        '/img/products/product-2-5.png',
      ],
      price: 1399,
      onSale: true,
      salePrice: 839,
      rating: 4,
      reviews: 17,
      stock: 10,
    },
    {
      id: '6426262806718',
      name: 'Set mobilier gradina Kring Thomas, masa, 6 scaune',
      category: 'garden',
      img: ['/img/products/product-3.png', '/img/products/product-3-1.png'],
      price: 2749,
      onSale: true,
      salePrice: 1899,
      rating: 4,
      reviews: 29,
      stock: 8,
    },
    {
      id: 'UE43RU7102KXXH',
      name: 'Televizor LED Smart Samsung, 108 cm, 43RU7102, 4K Ultra HD',
      category: 'electronics',
      img: [
        '/img/products/product-4.png',
        '/img/products/product-4-1.png',
        '/img/products/product-4-2.png',
        '/img/products/product-4-3.png',
        '/img/products/product-4-4.png',
        '/img/products/product-4-5.png',
        '/img/products/product-4-6.png',
        '/img/products/product-4-7.png',
        '/img/products/product-4-8.png',
      ],
      price: 1999,
      onSale: true,
      salePrice: 1599,
      rating: 4.5,
      reviews: 605,
      stock: 38,
    },
    {
      id: 'SMA105FZKUROM',
      name: 'Telefon mobil Samsung Galaxy A10, Dual Sim, 32GB, 4G, Black',
      category: 'electronics',
      img: [
        '/img/products/product-5.png',
        '/img/products/product-5-1.png',
        '/img/products/product-5-2.png',
        '/img/products/product-5-3.png',
        '/img/products/product-5-4.png',
      ],
      price: 699,
      onSale: true,
      salePrice: 599,
      rating: 4.5,
      reviews: 625,
      stock: 20,
    },
    {
      id: 'ACT12ETL',
      name:
        'Aparat de aer conditionat Star-Light ACT-12ETL, 3D Inverter, 12000 BTU, Functie incalzire, Clasa A++, Display',
      category: 'electronics',
      img: [
        '/img/products/product-6.png',
        '/img/products/product-6-1.png',
        '/img/products/product-6-2.png',
        '/img/products/product-6-3.png',
      ],
      price: 1699,
      onSale: true,
      salePrice: 1099,
      rating: 4,
      reviews: 127,
      stock: 12,
    },
    {
      id: 'HCNF317A',
      name:
        'Combina frigorifica Heinner HCNF-317A+, 317 l, No Frost, Display, Clasa A+, H185 cm',
      category: 'electronics',
      img: ['/img/products/product-7.png', '/img/products/product-7-1.png'],
      price: 2499,
      onSale: true,
      salePrice: 1429,
      rating: 4.5,
      reviews: 6,
      stock: 15,
    },
    {
      id: 'AKP7460IX',
      name:
        'Cuptor incorporabil Whirlpool AKP 7460, Electric, 65 l, Multifunctional, 8 functii, Inox antiamprenta',
      category: 'electronics',
      img: [
        '/img/products/product-8.png',
        '/img/products/product-8-1.png',
        '/img/products/product-8-2.png',
        '/img/products/product-8-3.png',
        '/img/products/product-8-4.png',
        '/img/products/product-8-5.png',
        '/img/products/product-8-6.png',
      ],
      price: 1849,
      onSale: true,
      salePrice: 1149,
      rating: 3.5,
      reviews: 14,
      stock: 21,
    },
    {
      id: 'RO3798',
      name: 'Aspirator fara sac Rowenta Compact Power RO3798, 750W, 1.5L',
      category: 'electronics',
      img: [
        '/img/products/product-9.png',
        '/img/products/product-9-1.png',
        '/img/products/product-9-2.png',
        '/img/products/product-9-3.png',
        '/img/products/product-9-4.png',
      ],
      price: 589,
      onSale: true,
      salePrice: 379,
      rating: 4.5,
      reviews: 129,
      stock: 9,
    },
    {
      id: '51095EXN',
      name: 'Telefon mobil Huawei P40 Pro, Dual SIM, 256GB, 8GB RAM, 5G',
      category: 'electronics',
      img: [
        '/img/products/product-10.png',
        '/img/products/product-10-1.png',
        '/img/products/product-10-2.png',
        '/img/products/product-10-3.png',
        '/img/products/product-10-4.png',
      ],
      price: 4599,
      onSale: true,
      salePrice: 4149,
      rating: 4.5,
      reviews: 47,
      stock: 4,
    },
    {
      id: '53010UAJ',
      name:
        'Laptop Huawei MateBook D15 2020 AMD Ryzen™ 5 3500U, 8GB, 256GB SSD, Full HD 15.6" ',
      category: 'electronics',
      img: [
        '/img/products/product-11.png',
        '/img/products/product-11-1.png',
        '/img/products/product-11-2.png',
        '/img/products/product-11-3.png',
        '/img/products/product-11-4.png',
        '/img/products/product-11-5.png',
        '/img/products/product-11-6.png',
        '/img/products/product-11-7.png',
        '/img/products/product-11-8.png',
      ],
      price: 2899,
      onSale: true,
      salePrice: 2499,
      rating: 5,
      reviews: 34,
      stock: 6,
    },
    {
      id: '9325901',
      name:
        'Consola SONY Playstation 4 Slim, 1TB, Jet Black + God of War + Horizon Zero Dawn CE + The Last of Us Remastered',
      category: 'electronics',
      img: [
        '/img/products/product-12.png',
        '/img/products/product-12-1.png',
        '/img/products/product-12-2.png',
        '/img/products/product-12-3.png',
        '/img/products/product-12-4.png',
        '/img/products/product-12-5.png',
        '/img/products/product-12-6.png',
        '/img/products/product-12-7.png',
      ],
      price: 1649,
      onSale: true,
      salePrice: 1549,
      rating: 5,
      reviews: 56,
      stock: 7,
    },
  ],
};

export default Data;
