const Data = [
	{
		id: '32HL4300H/A',
		name: 'Televizor LED Diamant, 80 cm, 32HL4300H/A, HD',
		category: 'electronics',
		img: '/img/products/product-1.png',
		price: 699,
		onSale: true,
		salePrice: 449,
		rating: 4.5,
		reviews: 367,
		stock: 11,
	},
	{
		id: 'PD91-4DB',
		name: 'Aspirator cu sac Electrolux PD91-4DB, 550W, 5 l',
		category: 'electronics',
		img: '/img/products/product-2.png',
		price: 1399,
		onSale: true,
		salePrice: 839,
		rating: 4,
		reviews: 17,
		stock: 9,
	},
	{
		id: 'HCNF-317A+',
		name:
			'Combina frigorifica Heinner HCNF-317A+, 317 l, No Frost, Display, Clasa A+, H185 cm',
		category: 'electronics',
		img: '/img/products/product-7.png',
		price: 2499,
		onSale: true,
		salePrice: 1429,
		rating: 4.8,
		reviews: 6,
		stock: 15,
	},
	{
		id: '6426262806718',
		name: 'Set mobilier gradina Kring Thomas, masa, 6 scaune',
		category: 'garden',
		img: '/img/products/product-3.png',
		price: 2749,
		onSale: true,
		salePrice: 1899,
		rating: 4.2,
		reviews: 29,
		stock: 8,
	},
	{
		id: 'UE43RU7102KXXH',
		name: 'Televizor LED Smart Samsung, 108 cm, 43RU7102, 4K Ultra HD',
		category: 'electronics',
		img: '/img/products/product-4.png',
		price: 1999,
		onSale: true,
		salePrice: 1599,
		rating: 4.5,
		reviews: 605,
		stock: 38,
	},
	{
		id: 'SM-A105FZKUROM',
		name: 'Telefon mobil Samsung Galaxy A10, Dual Sim, 32GB, 4G, Black',
		category: 'electronics',
		img: '/img/products/product-5.png',
		price: 699,
		onSale: false,
		salePrice: null,
		rating: 4.5,
		reviews: 625,
		stock: 20,
	},
	{
		id: 'ACT-12ETL',
		name:
			'Aparat de aer conditionat Star-Light ACT-12ETL, 3D Inverter, 12000 BTU, Functie incalzire, Clasa A++, Display',
		category: 'electronics',
		img: '/img/products/product-6.png',
		price: 1699,
		onSale: true,
		salePrice: 1099,
		rating: 4.3,
		reviews: 127,
		stock: 11,
	},
];

export default Data;
